brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "editorconfig"
brew "fzy"
brew "gist"
brew "git"
brew "git-lfs"
brew "gnupg", args: ["with-readline", "without-libusb"]
brew "grep"
brew "less"
brew "pinentry-mac"
brew "ripgrep"
brew "shellcheck"
brew "tidy-html5"
brew "tree"
brew "vim", args: ["with-custom-perl", "with-custom-python", "with-custom-ruby"]
brew "watch"
brew "youtube-dl"
cask "basictex"
cask "docker"
cask "vagrant"
cask "virtualbox"
