#!/usr/bin/env bash

CONFIG_PATH=~/.dotfiles

function relink() {
  if [[ -h "$1" ]]; then
    echo "Relinking $1"
    # Symbolic link? Then recreate.
    rm "$1"
    ln -sn "$2" "$1"
  elif [[ ! -e "$1" ]]; then
    echo "Linking $1"
    ln -sn "$2" "$1"
  else
    echo "$1 exists as a real file, skipping."
  fi
}

cd ~
relink .bash_profile ${CONFIG_PATH}/bash_profile
relink .bashrc ${CONFIG_PATH}/bashrc
relink .bash_aliases ${CONFIG_PATH}/bash_aliases
relink .gitconfig ${CONFIG_PATH}/git-config
relink .gitignore ${CONFIG_PATH}/git-ignore-global
relink .inputrc ${CONFIG_PATH}/inputrc
relink .vimrc ${CONFIG_PATH}/vimrc
relink bin ${CONFIG_PATH}/bin
relink .vim ${CONFIG_PATH}/vim