#!/bin/sh

set -e

dir=$(git rev-parse --show-toplevel 2>/dev/null)

test "$1" != "-u" || {
	git submodule update --init
	exit 0
}

link () {
	local src="$dir/$1"

	test "$(readlink $2)" = "$src" || {
		ln -vshf "$src" "$2"
	}
}

test -d "$HOME/.history" || mkdir -vp "$HOME/.history"

mkdir -vp vim/_backup vim/_tmp vim/_undo

link gitconfig		"$HOME/.gitconfig"
link gitignore		"$HOME/.gitignore"
link gitattributes	"$HOME/.gitattributes"
link bashrc		"$HOME/.bashrc"
link bash_profile	"$HOME/.bash_profile"
link bash_aliases	"$HOME/.bash_aliases"
link editrc		"$HOME/.editrc"
link hgrc		"$HOME/.hgrc"
link histignore		"$HOME/.history/histignore"
link inputrc		"$HOME/.inputrc"
link irbrc		"$HOME/.irbrc"
link sqliterc		"$HOME/.sqliterc"
link gdbinit		"$HOME/.gdbinit"
link valgrindrc		"$HOME/.valgrindrc"
link pinerc		"$HOME/.pinerc"
link gemrc		"$HOME/.gemrc"
link bin		"$HOME/bin"
link racketrc		"$HOME/.racketrc"
link vim		"$HOME/.vim"
link vimrc		"$HOME/vimrc"