#!/bin/sh
# shellcheck disable=SC2034
while read -r local_ref local_oid remote_ref remote_oid; do
  branch=${remote_ref#refs/heads/}
  case "$branch" in
    main|master)
      echo >&2 "pre-push: use --no-verify if you really want to push to ${branch}"
      exit 1
      ;;
  esac
done
