#!/bin/bash
set -eu

cd "$(git rev-parse --show-toplevel)"

bootstrap_git () {
  # shellcheck disable=SC2188
  [ -f "$HOME/.gitconfig" ] || >"$HOME/.gitconfig"

  if ! git config --get user.name >/dev/null; then
    printf "Name: "
    read -r name
    git config --global user.name "$name"
  fi

  if ! git config --get user.email >/dev/null; then
    printf "Email: "
    read -r email
    git config --global user.email "$email"
  fi
}

bootstrap_vim () {
  mkdir -p vim/{_backup,_swap,_undo}
  script/vim-packages
}

bootstrap_less () {
  lesskey -- lesskey
}

bootstrap_git
bootstrap_vim
bootstrap_less
script/link
