#!/bin/sh
set -eu

files='
  bash_profile
  bashrc
  config/git
  curlrc
  editorconfig
  editrc
  eslintrc.json
  gemrc
  inputrc
  irbrc
  local/bin
  psqlrc
  shrc
  sqliterc
  valgrindrc
  vim
  vimrc
'

repo=$(git rev-parse --show-toplevel)

for file in $files; do
  basename=${file##*/}

  case "$file" in
    */*)
      dirname="$HOME/.${file%/*}"
      ;;
    *)
      dirname=$HOME
      basename=".${basename}"
      ;;
  esac

  source="$repo/$file"
  target="$dirname/$basename"

  # shellcheck disable=SC2166
  if [ ! -L "$target" ] && [ -f "$target" -o -d "$target" ]; then
    echo "path $target already exists, skipping" >&2
    continue
  fi

  mkdir -p "$dirname"
  ln -sfnv "$source" "$target"
done
